/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Domain.Vehicle;
import File.FileVehicle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class JFrameVehicle extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEmployee
     */
    Vehicle vehicle;
    File file;
    Vehicle vehicleTemp;
    FileVehicle fileVehicle;
    boolean isAmericanTemp;

    public JFrameVehicle() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        isAmericanTemp = false;
        file = new File("./Vehicle.dat");
        try {
            fileVehicle = new FileVehicle(file);
        } catch (IOException ex) {
            Logger.getLogger(JFrameVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     *
     * @return @throws IOException
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Message = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Background = new javax.swing.JLabel();
        jTabbedPaneEmployee = new javax.swing.JTabbedPane();
        jPanelInsert = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelIdentification = new javax.swing.JLabel();
        labelDayHours = new javax.swing.JLabel();
        labelNigthHours = new javax.swing.JLabel();
        InsertVehicle = new javax.swing.JButton();
        jTextFieldInsertName = new javax.swing.JTextField();
        jTextFieldInsertYear = new javax.swing.JTextField();
        jTextFieldInsertMileage = new javax.swing.JTextField();
        jTextFieldInsertSerie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldInsertWeight = new javax.swing.JTextField();
        jComboBoxInsertAmerican = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonBackPrevious = new javax.swing.JButton();
        jPanelSearch = new javax.swing.JPanel();
        jLabelNameSearch = new javax.swing.JLabel();
        jTextFieldNameSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNameSearch = new javax.swing.JTextArea();
        jButtonSearchVehicle = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonBackPrevious4 = new javax.swing.JButton();
        jPanelDelete = new javax.swing.JPanel();
        labelIdentificationDelete = new javax.swing.JLabel();
        jTextFieldSerieDelete = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        jLabelMessageDelete = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonBackPrevious1 = new javax.swing.JButton();
        jPanelUpdate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearchSerie = new javax.swing.JTextField();
        jButtonSearchSerie = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUpdateName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUpdateMileage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUpdateYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonUpdateVehicle = new javax.swing.JButton();
        jComboBoxAmerican = new javax.swing.JComboBox<>();
        jLabelUpdateAmerican = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUpdateWeight = new javax.swing.JTextField();
        jButtonBackPrevious2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaVehicles = new javax.swing.JTextArea();
        jButtonBackPrevious3 = new javax.swing.JButton();

        Message.setBackground(new java.awt.Color(204, 255, 153));
        Message.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        Message.setText("Enter the name");

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReistryAutomobile.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jTabbedPaneEmployee.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPaneEmployee.setMinimumSize(new java.awt.Dimension(600, 600));
        jTabbedPaneEmployee.setPreferredSize(new java.awt.Dimension(600, 600));
        jTabbedPaneEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneEmployeeMouseClicked(evt);
            }
        });

        jPanelInsert.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelInsert.setPreferredSize(new java.awt.Dimension(600, 600));

        labelName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelName.setText("Brand");

        labelLastName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelLastName.setText("Year");

        labelIdentification.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelIdentification.setText("Mileage");

        labelDayHours.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelDayHours.setText("American");

        labelNigthHours.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelNigthHours.setText("Serie");

        InsertVehicle.setBackground(new java.awt.Color(76, 175, 80));
        InsertVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InsertVehicle.setForeground(new java.awt.Color(255, 255, 255));
        InsertVehicle.setText("Insert");
        InsertVehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertVehicleActionPerformed(evt);
            }
        });

        jTextFieldInsertName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldInsertName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsertNameActionPerformed(evt);
            }
        });

        jTextFieldInsertYear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jTextFieldInsertMileage.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldInsertMileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsertMileageActionPerformed(evt);
            }
        });

        jTextFieldInsertSerie.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldInsertSerie.setMinimumSize(new java.awt.Dimension(6, 30));
        jTextFieldInsertSerie.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Add vehicle");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Weight");

        jTextFieldInsertWeight.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jComboBoxInsertAmerican.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxInsertAmerican.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jComboBoxInsertAmerican.setMinimumSize(new java.awt.Dimension(45, 30));
        jComboBoxInsertAmerican.setPreferredSize(new java.awt.Dimension(45, 30));
        jComboBoxInsertAmerican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInsertAmericanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("km");

        jLabelMessage.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("kilograms");

        jButtonBackPrevious.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBackPrevious.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_home_black_18dp.png"))); // NOI18N
        jButtonBackPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInsertLayout = new javax.swing.GroupLayout(jPanelInsert);
        jPanelInsert.setLayout(jPanelInsertLayout);
        jPanelInsertLayout.setHorizontalGroup(
            jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(232, 232, 232))
            .addGroup(jPanelInsertLayout.createSequentialGroup()
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldInsertName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTextFieldInsertYear, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTextFieldInsertWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertLayout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(labelLastName)
                                    .addComponent(labelIdentification)
                                    .addComponent(labelName))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNigthHours)
                                    .addComponent(labelDayHours))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldInsertMileage, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jComboBoxInsertAmerican, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InsertVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInsertSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonBackPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanelInsertLayout.setVerticalGroup(
            jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInsertWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInsertName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInsertYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldInsertMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInsertAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDayHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInsertSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNigthHours, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(InsertVehicle)
                .addGap(13, 13, 13)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBackPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPaneEmployee.addTab("Insert", jPanelInsert);

        jPanelSearch.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelSearch.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabelNameSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelNameSearch.setText("Serie");

        jTextFieldNameSearch.setMinimumSize(new java.awt.Dimension(6, 30));
        jTextFieldNameSearch.setPreferredSize(new java.awt.Dimension(6, 30));
        jTextFieldNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameSearchActionPerformed(evt);
            }
        });
        jTextFieldNameSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNameSearchKeyReleased(evt);
            }
        });

        jTextAreaNameSearch.setColumns(20);
        jTextAreaNameSearch.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNameSearch);

        jButtonSearchVehicle.setBackground(new java.awt.Color(76, 175, 80));
        jButtonSearchVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearchVehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchVehicle.setText("Search");
        jButtonSearchVehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearchVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchVehicleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Search vehicle");

        jButtonBackPrevious4.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBackPrevious4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_home_black_18dp.png"))); // NOI18N
        jButtonBackPrevious4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPrevious4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPrevious4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabelNameSearch)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jButtonSearchVehicle)
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBackPrevious4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchVehicle)
                    .addComponent(jTextFieldNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonBackPrevious4)
                .addGap(76, 76, 76))
        );

        jTabbedPaneEmployee.addTab("Search", jPanelSearch);

        jPanelDelete.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelDelete.setPreferredSize(new java.awt.Dimension(600, 600));

        labelIdentificationDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelIdentificationDelete.setText("Serie");

        jTextFieldSerieDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Delete vehicle");

        jButtonBackPrevious1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBackPrevious1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_home_black_18dp.png"))); // NOI18N
        jButtonBackPrevious1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPrevious1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeleteLayout = new javax.swing.GroupLayout(jPanelDelete);
        jPanelDelete.setLayout(jPanelDeleteLayout);
        jPanelDeleteLayout.setHorizontalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDeleteLayout.createSequentialGroup()
                        .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabelMessageDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel13)))
                        .addGap(0, 209, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBackPrevious1))
                    .addGroup(jPanelDeleteLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                                .addComponent(labelIdentificationDelete)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSerieDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButtonDelete)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDeleteLayout.setVerticalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel13)
                .addGap(43, 43, 43)
                .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificationDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSerieDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelMessageDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jButtonBackPrevious1)
                .addGap(67, 67, 67))
        );

        jTabbedPaneEmployee.addTab("Delete", jPanelDelete);

        jPanelUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelUpdate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanelUpdate.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelUpdate.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Update vehicle data");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Serie");

        jButtonSearchSerie.setBackground(new java.awt.Color(76, 175, 80));
        jButtonSearchSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearchSerie.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchSerie.setText("Search");
        jButtonSearchSerie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearchSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchSerieActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Brand");

        jTextFieldUpdateName.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Mileage");

        jTextFieldUpdateMileage.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Year");

        jTextFieldUpdateYear.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("American");

        jButtonUpdateVehicle.setBackground(new java.awt.Color(76, 175, 80));
        jButtonUpdateVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonUpdateVehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateVehicle.setText("Update");
        jButtonUpdateVehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdateVehicle.setEnabled(false);
        jButtonUpdateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateVehicleActionPerformed(evt);
            }
        });

        jComboBoxAmerican.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxAmerican.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jComboBoxAmerican.setEnabled(false);
        jComboBoxAmerican.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBoxAmericanAncestorRemoved(evt);
            }
        });

        jLabelUpdateAmerican.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Weight");

        jTextFieldUpdateWeight.setEditable(false);

        jButtonBackPrevious2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBackPrevious2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_home_black_18dp.png"))); // NOI18N
        jButtonBackPrevious2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPrevious2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPrevious2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("kg");

        javax.swing.GroupLayout jPanelUpdateLayout = new javax.swing.GroupLayout(jPanelUpdate);
        jPanelUpdate.setLayout(jPanelUpdateLayout);
        jPanelUpdateLayout.setHorizontalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateLayout.createSequentialGroup()
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelUpdateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4))
                    .addGroup(jPanelUpdateLayout.createSequentialGroup()
                        .addGap(0, 130, Short.MAX_VALUE)
                        .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSearchSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateLayout.createSequentialGroup()
                                    .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                            .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel14))
                                            .addGap(31, 31, 31))
                                        .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldUpdateYear)
                                        .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                            .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateLayout.createSequentialGroup()
                                                    .addComponent(jButtonUpdateVehicle)
                                                    .addGap(7, 7, 7)))
                                            .addComponent(jLabelUpdateAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldUpdateWeight))))
                            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(jTextFieldUpdateMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jLabel15)
                .addGap(158, 158, 158))
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdateLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jButtonSearchSerie))
                    .addGroup(jPanelUpdateLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonBackPrevious2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUpdateLayout.setVerticalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSearchSerie)
                .addGap(35, 35, 35)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jLabelUpdateAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdateLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14))
                    .addGroup(jPanelUpdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUpdateWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdateVehicle)
                .addGap(31, 31, 31)
                .addComponent(jButtonBackPrevious2)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPaneEmployee.addTab("Update", jPanelUpdate);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Vehicles");

        jTextAreaVehicles.setColumns(20);
        jTextAreaVehicles.setRows(5);
        jScrollPane2.setViewportView(jTextAreaVehicles);

        jButtonBackPrevious3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBackPrevious3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_home_black_18dp.png"))); // NOI18N
        jButtonBackPrevious3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPrevious3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPrevious3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBackPrevious3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel11)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBackPrevious3)
                .addGap(49, 49, 49))
        );

        jTabbedPaneEmployee.addTab("Vehicles", jPanel1);

        getContentPane().add(jTabbedPaneEmployee);
        jTabbedPaneEmployee.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneEmployeeMouseClicked

        try {
            List<Vehicle> vehiclesList = fileVehicle.getAllVehicles();
            String vehicles = "";
            for (int i = 0; i < vehiclesList.size(); i++) {
                vehicles += vehiclesList.get(i).toString() + "\n-----------------------\n";
            }

            jTextAreaVehicles.setText(vehicles);
        } catch (IOException ex) {
            Logger.getLogger(JFrameVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPaneEmployeeMouseClicked

    private void jComboBoxAmericanAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxAmericanAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAmericanAncestorRemoved

    private void jButtonUpdateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateVehicleActionPerformed
        try {
            vehicleTemp.setName(jTextFieldUpdateName.getText());
            vehicleTemp.setAge(Integer.parseInt(jTextFieldUpdateYear.getText()));

            if (jComboBoxAmerican.getSelectedItem().toString().equalsIgnoreCase("Yes")) {
                isAmericanTemp = true;
            } else {
                isAmericanTemp = false;
            }
            vehicleTemp.setAmericano(isAmericanTemp);

            fileVehicle.updateRecord(vehicleTemp);
            jTextFieldUpdateName.setText("");
            jTextFieldUpdateYear.setText("");
            jLabelUpdateAmerican.setText("");
            jTextFieldUpdateMileage.setText("");
            jTextFieldInsertWeight.setText("");
            jTextFieldSearchSerie.setText("");
            jTextFieldUpdateWeight.setText("");

            jTextFieldUpdateName.setEditable(false);
            jTextFieldUpdateYear.setEditable(false);
            jComboBoxAmerican.setEnabled(false);
            jButtonUpdateVehicle.setEnabled(false);
            jTextFieldSearchSerie.setEditable(true);
            jTextFieldUpdateWeight.setEditable(false);
            jButtonSearchSerie.setEnabled(true);

        } catch (IOException ex) {
            Logger.getLogger(JFrameVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonUpdateVehicleActionPerformed

    private void jButtonSearchSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchSerieActionPerformed
        try {
            int serie = Integer.parseInt(jTextFieldSearchSerie.getText());

            vehicleTemp = fileVehicle.searchBySeries(serie);

            if (vehicleTemp != null) {
                jTextFieldUpdateName.setEditable(true);
                jTextFieldUpdateYear.setEditable(true);
                jComboBoxAmerican.setEnabled(true);
                jButtonUpdateVehicle.setEnabled(true);
                jTextFieldSearchSerie.setEditable(false);
                jButtonSearchSerie.setEnabled(false);

                jTextFieldUpdateName.setText(vehicleTemp.getName());
                jTextFieldUpdateYear.setText(String.valueOf(vehicleTemp.getAge()));
                if (vehicleTemp.isAmericano() == true) {
                    jLabelUpdateAmerican.setText("Yes");
                } else {
                    jLabelUpdateAmerican.setText("No");
                }

                jTextFieldUpdateMileage.setText(String.valueOf(vehicleTemp.getMileage()));
                jTextFieldUpdateWeight.setText(String.valueOf(vehicleTemp.getWeight()));
                jTextFieldSearchSerie.setText(String.valueOf(vehicleTemp.getSerie()));

            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSearchSerieActionPerformed

    private void jButtonBackPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPreviousActionPerformed
        WindowRegistration frame_backhome = new WindowRegistration();
        frame_backhome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackPreviousActionPerformed

    private void jComboBoxInsertAmericanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInsertAmericanActionPerformed

    }//GEN-LAST:event_jComboBoxInsertAmericanActionPerformed

    private void jTextFieldInsertMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsertMileageActionPerformed
        //        jTextFieldName.getText(),jTextFieldLastName.getText(),
        //                                   Integer.parseInt(jTextFieldIdentification.getText()),
        //                                    "" , Integer.parseInt(jTextFieldDayHours.getText()),
        //                                   Integer.parseInt(jTextFieldNigthHours.getText()),isQualified
    }//GEN-LAST:event_jTextFieldInsertMileageActionPerformed

    private void jTextFieldInsertNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsertNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsertNameActionPerformed

    private void InsertVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertVehicleActionPerformed

        ////       if(!file.exists())
        //            file = new File("./Vehicle.dat");
        jLabelMessage.setVisible(true);
        jLabelMessage.setText("Successfully inserted vehicle");
        int weightV = Integer.parseInt(jTextFieldInsertWeight.getText());
        String nameV = jTextFieldInsertName.getText();
        int yearV = Integer.parseInt(jTextFieldInsertYear.getText());
        float mileageV = Float.parseFloat(jTextFieldInsertMileage.getText());

        if (jComboBoxInsertAmerican.getSelectedItem().toString().equalsIgnoreCase("Yes")) {
            isAmericanTemp = true;
        }
        boolean isAmerican = isAmericanTemp;
        int serieV = Integer.parseInt(jTextFieldInsertSerie.getText());

        vehicle = new Vehicle(weightV, nameV, yearV, mileageV, isAmerican, serieV);
        jTextFieldInsertName.setText("");
        jTextFieldInsertWeight.setText("");
        jTextFieldInsertMileage.setText("");
        jTextFieldInsertYear.setText("");
        jTextFieldInsertSerie.setText("");
          
        try {
            fileVehicle = new FileVehicle(file);
            fileVehicle.addEndRecord(vehicle);
        } catch (IOException ex) {
            Logger.getLogger(JFrameVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }

        //jLabelMessage.setText("Successfully inserted vehicle");
    }//GEN-LAST:event_InsertVehicleActionPerformed

    private void jButtonBackPrevious2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPrevious2ActionPerformed
        WindowRegistration frame_backhome = new WindowRegistration();
        frame_backhome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackPrevious2ActionPerformed

    private void jButtonBackPrevious3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPrevious3ActionPerformed
        WindowRegistration frame_backhome = new WindowRegistration();
        frame_backhome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackPrevious3ActionPerformed

    private void jButtonSearchVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchVehicleActionPerformed

        int serie = Integer.parseInt(jTextFieldNameSearch.getText());

        try {
            if (fileVehicle.searchBySeries(serie) != null) {
                jTextAreaNameSearch.setText(fileVehicle.searchBySeries(serie).toString());
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSearchVehicleActionPerformed

    private void jTextFieldNameSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameSearchKeyReleased
        String information = "";

        //        for (int i = 0; i < fileVehicle.length(); i++) {
        //            if(fileVehicle.empiezaPor(jTextFieldNameSearch.getText()))
        //                information+=fileVehicle.get(i).toString()+"\n";
        //            jTextAreaNameSearch.setText(information);
        //        }
    }//GEN-LAST:event_jTextFieldNameSearchKeyReleased

    private void jTextFieldNameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameSearchActionPerformed

    private void jButtonBackPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPrevious1ActionPerformed
        WindowRegistration frame_backhome = new WindowRegistration();
        frame_backhome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackPrevious1ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int action = JOptionPane.showConfirmDialog(this, "The vehicle with serie " + jTextFieldSerieDelete.getText() + " will be deleted.\nWould you like to continue?", "Warning", 1);

        if (JOptionPane.YES_OPTION == action) {
            try {
                String delete_by_serie = jTextFieldSerieDelete.getText();
                fileVehicle.deleteVehicle(Integer.parseInt(delete_by_serie));
                jLabelMessageDelete.setText("Delete");
                jTextFieldSerieDelete.setText("");
            } catch (IOException ex) {
                Logger.getLogger(JFrameVehicle.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelMessageDelete.setText("Operation cancelled");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonBackPrevious4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPrevious4ActionPerformed
        WindowRegistration frame_backhome = new WindowRegistration();
        frame_backhome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackPrevious4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton InsertVehicle;
    private javax.swing.JLabel Message;
    private javax.swing.JButton jButtonBackPrevious;
    private javax.swing.JButton jButtonBackPrevious1;
    private javax.swing.JButton jButtonBackPrevious2;
    private javax.swing.JButton jButtonBackPrevious3;
    private javax.swing.JButton jButtonBackPrevious4;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearchSerie;
    private javax.swing.JButton jButtonSearchVehicle;
    private javax.swing.JButton jButtonUpdateVehicle;
    private javax.swing.JComboBox<String> jComboBoxAmerican;
    private javax.swing.JComboBox<String> jComboBoxInsertAmerican;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelMessageDelete;
    private javax.swing.JLabel jLabelNameSearch;
    private javax.swing.JLabel jLabelUpdateAmerican;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDelete;
    private javax.swing.JPanel jPanelInsert;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPaneEmployee;
    private javax.swing.JTextArea jTextAreaNameSearch;
    private javax.swing.JTextArea jTextAreaVehicles;
    private javax.swing.JTextField jTextFieldInsertMileage;
    private javax.swing.JTextField jTextFieldInsertName;
    private javax.swing.JTextField jTextFieldInsertSerie;
    private javax.swing.JTextField jTextFieldInsertWeight;
    private javax.swing.JTextField jTextFieldInsertYear;
    private javax.swing.JTextField jTextFieldNameSearch;
    private javax.swing.JTextField jTextFieldSearchSerie;
    private javax.swing.JTextField jTextFieldSerieDelete;
    private javax.swing.JTextField jTextFieldUpdateMileage;
    private javax.swing.JTextField jTextFieldUpdateName;
    private javax.swing.JTextField jTextFieldUpdateWeight;
    private javax.swing.JTextField jTextFieldUpdateYear;
    private javax.swing.JLabel labelDayHours;
    private javax.swing.JLabel labelIdentification;
    private javax.swing.JLabel labelIdentificationDelete;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNigthHours;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
