/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.plaf.DesktopPaneUI;

public class WindowRegistration extends javax.swing.JFrame {

    /**
     * Creates new form WindowRegistration
     */
    public WindowRegistration() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBackPrevious4 = new javax.swing.JButton();
        windowPrincipal = new javax.swing.JDesktopPane();
        jButtonHeavyMacinery = new javax.swing.JButton();
        jButtonVehicle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonDriver = new javax.swing.JButton();
        jButtonJanitor = new javax.swing.JButton();
        jButtonAdministrative = new javax.swing.JButton();

        jButtonBackPrevious4.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBackPrevious4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackPrevious4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_home_black_18dp.png"))); // NOI18N
        jButtonBackPrevious4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPrevious4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPrevious4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registry");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(30, 30));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        windowPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        windowPrincipal.setMinimumSize(new java.awt.Dimension(600, 600));

        jButtonHeavyMacinery.setBackground(new java.awt.Color(0, 104, 78));
        jButtonHeavyMacinery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHeavyMacinery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHeavyMacinery.setText("Heavy Machinery");
        jButtonHeavyMacinery.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonHeavyMacinery.setFocusable(true);
        jButtonHeavyMacinery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHeavyMacineryActionPerformed(evt);
            }
        });
        windowPrincipal.add(jButtonHeavyMacinery);
        jButtonHeavyMacinery.setBounds(410, 450, 140, 40);

        jButtonVehicle.setBackground(new java.awt.Color(0, 104, 78));
        jButtonVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVehicle.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVehicle.setText("Vehicle");
        jButtonVehicle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVehicle.setFocusable(false);
        jButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehicleActionPerformed(evt);
            }
        });
        windowPrincipal.add(jButtonVehicle);
        jButtonVehicle.setBounds(410, 510, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        windowPrincipal.add(jLabel1);
        jLabel1.setBounds(80, 190, 440, 140);

        jButtonDriver.setBackground(new java.awt.Color(0, 104, 78));
        jButtonDriver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDriver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDriver.setText("Driver");
        jButtonDriver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDriver.setFocusable(true);
        jButtonDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDriverActionPerformed(evt);
            }
        });
        windowPrincipal.add(jButtonDriver);
        jButtonDriver.setBounds(20, 510, 140, 40);

        jButtonJanitor.setBackground(new java.awt.Color(0, 104, 78));
        jButtonJanitor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonJanitor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJanitor.setText("Janitor");
        jButtonJanitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJanitorActionPerformed(evt);
            }
        });
        windowPrincipal.add(jButtonJanitor);
        jButtonJanitor.setBounds(20, 460, 140, 40);

        jButtonAdministrative.setBackground(new java.awt.Color(0, 104, 78));
        jButtonAdministrative.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAdministrative.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdministrative.setText("Administrative");
        windowPrincipal.add(jButtonAdministrative);
        jButtonAdministrative.setBounds(20, 410, 140, 40);

        getContentPane().add(windowPrincipal);
        windowPrincipal.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehicleActionPerformed
      JFrameVehicle jve = new JFrameVehicle();
        jve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVehicleActionPerformed

    private void jButtonHeavyMacineryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHeavyMacineryActionPerformed
        JFrameHeavyMachinery jem = new JFrameHeavyMachinery();
          
        jem.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonHeavyMacineryActionPerformed

    private void jButtonBackPrevious4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPrevious4ActionPerformed
        WindowRegistration frame_backhome = new WindowRegistration();
        frame_backhome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackPrevious4ActionPerformed

    private void jButtonDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDriverActionPerformed
         JFrameDriver em = new JFrameDriver();
         em.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonDriverActionPerformed

    private void jButtonJanitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJanitorActionPerformed
       JFrameJanitor janitor=new JFrameJanitor();
      janitor.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonJanitorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministrative;
    private javax.swing.JButton jButtonBackPrevious4;
    private javax.swing.JButton jButtonDriver;
    private javax.swing.JButton jButtonHeavyMacinery;
    private javax.swing.JButton jButtonJanitor;
    private javax.swing.JButton jButtonVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDesktopPane windowPrincipal;
    // End of variables declaration//GEN-END:variables
}
